# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# Template -Dtemplate=docker-jar
version: 2.1
orbs:
  marvel: scoperetail/marvel@2.15.0

workflows:
  build-and-test:
    jobs:
      - marvel/maven-release-ui-docker:
          context:
            - OSSRH
            - DOCKER_SCOPERETAIL
            - SLACK
            - ARTIFACTORY
          filters:
            branches:
              only:
                - master
                - /HOTFIX-.*/
                
